//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by xfilter.rc
//
#define IDS_SIGNED_APP                  1
#define IDS_UPDATE_MESSAGE              2
#define IDLOAD                          3
#define IDC_ADVANCE                     3
#define IDS_CAPTION                     3
#define IDS_ERROR_CANT_RUNREGISTER      4
#define IDS_ERROR_CANT_RUN_USERREG      4
#define IOCTL_SET_ACL                   5
#define IDS_ERROR_CANT_RUN_FILUP        5
#define ID_LOAD_VXD                     6
#define IDS_UPDATE_MESSAGE_EX           6
#define ID_UNLOAD_VXD                   7
#define ID_PRINT_PROCESS                8
#define IDD_XFILTER_DIALOG              102
#define IDB_SPLASH                      103
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        129
#define IDD_ACL_APP                     137
#define IDD_SYSTEM_SET                  138
#define IDD_ABOUT                       139
#define IDD_ACL_NET                     141
#define IDD_ACL_TIME                    142
#define IDD_DIALOG_REGISTER             146
#define IDB_BITMAP1                     149
#define IDB_MAIN                        149
#define IDB_BITMAP2                     150
#define IDB_BUTTON                      150
#define IDI_ALERT_SET                   155
#define IDI_COMMON_SET                  158
#define IDB_CLOSE                       170
#define IDB_MIN                         171
#define IDB_PASSECK2                    172
#define IDB_PASSECK_FOCUS               172
#define IDB_PASSECK1                    174
#define IDB_PASSECK_NORMAL              174
#define IDI_ICONHAND                    175
#define IDC_HAND                        176
#define IDI_SMALL_MESSAGE               177
#define IDI_SMALL_NULL                  178
#define IDI_SMALL_ALERT                 180
#define IDB_GREEN_FOCUS                 195
#define IDB_GREEN_NORMAL                196
#define IDB_GREEN_SELECT                197
#define IDB_RED_FOCUS                   198
#define IDB_RED_NORMAL                  199
#define IDB_RED_SELECT                  200
#define IDB_YELLOW_FOCUS                201
#define IDB_YELLOW_NORMAL               202
#define IDI_SMALL_QUERY                 202
#define IDB_YELLOW_SELECT               203
#define IDI_SMALL_PASS                  203
#define IDI_SMALL_DENY                  204
#define IDD_MONITOR_SUB                 227
#define IDD_LOG_SUB                     228
#define IDD_ACL_SUB                     229
#define IDB_SYSTEM_SET                  251
#define IDD_PARAMETER_SUB               278
#define IDD_ONLINE                      279
#define IDB_RADIO_NORMAL                280
#define IDB_RADIO_SELECT                281
#define IDD_ACL_WEB                     282
#define IDD_ACL_NNB                     283
#define IDD_ACL_ICMP                    284
#define IDD_ACL_TORJAN                  286
#define IDD_ACL_APP_ADD                 289
#define IDD_ACL                         291
#define IDB_INFO                        297
#define IDB_ACL                         298
#define IDD_ACL_NET_ADD                 299
#define IDD_ACL_WEB_ADD                 300
#define IDD_ACL_ICMP_ADD                302
#define IDD_ACL_NNB_ADD                 303
#define IDB_QUERY                       304
#define IDD_ACL_QUERY                   305
#define IDR_NULLAPP                     306
#define IDB_TOPMOST_NORMAL              309
#define IDB_TOPMOST_SELECT              310
#define IDI_SMALL_PASS_SEND             318
#define IDI_SMALL_PASS_RECV             319
#define IDI_SMALL_PASS_RDSD             320
#define IDI_SMALL_DENY_RDSD             321
#define IDI_SMALL_DENY_RECV             322
#define IDI_SMALL_DENY_SEND             323
#define IDI_SMALL_QUERY_RDSD            324
#define IDI_SMALL_QUERY_RECV            325
#define IDI_SMALL_QUERY_SEND            326
#define IDC_BUTTON_SCROLL               1001
#define IDC_BUTTON_APPLICATION          1001
#define IDC_BUTTON_MONITOR              1003
#define IDC_MAIN                        1004
#define IDC_BUTTON_CLEAR                1004
#define IDC_ABOUT_LABLE_COPYRIGHT1      1008
#define IDC_ACL_LIST                    1008
#define IDC_ABOUT_LABLE_COPYRIGHT2      1009
#define IDC_ABOUT_LABLE_COPYRIGHT3      1010
#define IDC_ABOUT_LABLE_WARNING         1011
#define IDC_START_DATE                  1011
#define IDC_ABOUT_LABLE_ACCREDIT_TO     1012
#define IDC_STOP_DATE                   1012
#define IDC_END_DATE                    1012
#define IDC_MONITOR                     1013
#define IDC_ABOUT_LABLE_WEB_ADDRESS     1013
#define IDC_LOG                         1014
#define IDC_ABOUT_LABLE_EMAIL           1014
#define IDC_START_TIME                  1014
#define IDC_ACL                         1015
#define IDC_ABOUT_LABLE_WEB_ADDRESS_LABLE 1015
#define IDC_WORK_MODE                   1015
#define IDC_PARAMETER                   1016
#define IDC_ABOUT_LABLE_EMAIL_LABLE     1016
#define IDC_STOP_TIME                   1016
#define IDC_END_TIME                    1016
#define IDC_ONLINE                      1017
#define IDC_ABOUT_LABLE_INFO            1017
#define IDC_ABOUT_LABLE_COPYRIGHT4      1017
#define IDC_SYSTEMSET                   1018
#define IDC_ABOUT_LABLE_AUTHOR          1018
#define IDC_ACL_RADIO_PASS              1018
#define IDC_ABOUT_LABLE_INFO2           1018
#define IDC_SYSTEM_SET_CHECK_LOG        1019
#define IDC_ABOUT_LABLE_COPYRIGHT       1019
#define IDC_ACL_RADIO_QUERY             1019
#define IDC_RADIO_PASS_AND_ADD_ACL      1019
#define IDC_ABOUT_LABLE_INFO3           1019
#define IDC_ABOUT                       1020
#define IDC_SYSTEM_SET_LIST_LOG_SIZE    1020
#define IDC_ACL_RADIO_DENY              1020
#define IDC_CLOSE                       1021
#define IDC_SYSTEM_SET_CHECK_AUTOSTART  1021
#define IDC_ACL_RADIO_DENYOUT           1021
#define IDC_COMBO_APPLICATION           1021
#define IDC_MIN                         1022
#define IDC_SYSTEM_SET_CHECK_ALERT_PCSPEAKER 1022
#define IDC_ACL_BUTTON_EDIT             1022
#define IDC_LOG_QUERY_RESULT_LIST_LABLE 1022
#define IDC_LABEL_RESULT_LIST           1022
#define IDC_COMBO_REMOTE_NET            1022
#define IDC_ABOUT_LABLE_EMAIL_TORJAN    1022
#define IDC_PASSECK                     1023
#define IDC_SYSTEM_SET_CHECK_ALERT_DIALOG 1023
#define IDC_ACL_BUTTON_DELETE           1023
#define IDC_COMBO_ACCESS_TIME           1023
#define IDC_ABOUT_LABLE_EMAIL_LABLE2    1023
#define IDC_GREEN                       1024
#define IDC_SYSTEM_SET_CHECK_SPLASH     1024
#define IDC_ACL_BUTTON_CANCEL           1024
#define IDC_SET_TIME_CHECK_THURSDAY     1024
#define IDC_COMBO_ACTION                1024
#define IDC_YELLOW                      1025
#define IDC_SET_TIME_CHECK_FRIDAY       1025
#define IDC_COMBO_DIRECTION             1025
#define IDC_RED                         1026
#define IDC_SET_TIME_CHECK_SATURDAY     1026
#define IDC_COMBO_SERVICE_TYPE          1026
#define IDC_EDIT_SERVICE_PORT           1027
#define IDC_TOPMOST                     1027
#define IDC_ACL_BUTTON_ADD              1028
#define IDC_EDIT_LOCAL_PORT             1028
#define IDC_BACKGROUND                  1029
#define IDC_BUTTON_QUERY                1029
#define IDC_ACL_BUTTON_APPLY            1029
#define IDC_NET_TREE                    1029
#define IDC_EDIT_MEMO                   1029
#define IDC_REG_EDIT_EMAIL              1029
#define IDC_REG_EDIT_ADDRESS            1030
#define IDC_MONITOR_APP                 1031
#define IDC_REG_EDIT_EMAIL2             1031
#define IDC_LOG_NNB                     1032
#define IDC_SUB_PARENT                  1032
#define IDC_ACL_APPLICATION_LABLE       1032
#define IDC_MONITOR_NNB                 1033
#define IDC_SYSTEM_SET_LABLE_LOG        1033
#define IDC_ACL_REMOTE_NET_LABLE        1033
#define IDC_LOG_ICMP                    1034
#define IDC_SYSTEM_SET_LABLE_AUTO_START 1034
#define IDC_ACL_ACCESS_TIME_LABLE       1034
#define IDC_SYSTEM_SET_LABLE_WELCOME    1035
#define IDC_ACL_ACTION_LABLE            1035
#define IDC_SYSTEM_SET_LABLE_AUDIO_ALERT 1036
#define IDC_ACL_DERECTION_LABLE         1036
#define IDC_SYSTEM_SET_LABLE_ICON_ALERT 1037
#define IDC_ACL_SERVICE_TYPE_LABLE      1037
#define IDC_LABLE_TITLE                 1038
#define IDC_ACL_SERVICE_PORT_LABLE      1038
#define IDC_MONITOR_ICMP                1039
#define IDC_ACL_SUB_PARENT              1039
#define IDC_LABEL_LOCAL_PORT            1039
#define IDC_REG_LABEL_GENDER            1039
#define IDC_ACL_APP                     1040
#define IDC_LABEL_MEM                   1040
#define IDC_REG_LABEL_ZIP               1040
#define IDC_MONITOR_PORT                1041
#define IDC_ACL_TORJAN                  1041
#define IDC_TIME_TREE                   1041
#define IDC_REG_LABEL_GENDER2           1041
#define IDC_ACL_WEB                     1042
#define IDC_SECURITY                    1042
#define IDC_LABEL_WEEK                  1042
#define IDC_MONITOR_LINE                1043
#define IDC_ACL_TIME                    1043
#define IDC_SET_TIME_CHECK_SUNDAY       1043
#define IDC_REG_LABEL_BIRTHDAY          1043
#define IDC_ACL_NNB                     1044
#define IDC_COMBO_SET                   1044
#define IDC_SET_TIME_CHECK_MONDAY       1044
#define IDC_REG_LABEL_METIER            1044
#define IDC_LOG_APP                     1045
#define IDC_ACL_NET                     1045
#define IDC_SET_TIME_CHECK_TUESDAY      1045
#define IDC_REG_LABEL_ADDRESS           1045
#define IDC_ACL_ICMP                    1046
#define IDC_SET_TIME_CHECK_WEDNESDAY    1046
#define IDC_REG_LABEL_DUTY              1046
#define IDC_REG_LABEL_DEGREE            1047
#define IDC_REG_LABEL_SALARY            1048
#define IDC_LABEL_PASSALL               1049
#define IDC_REG_LABEL_INC               1049
#define IDC_LABEL_DENYALL               1050
#define IDC_REG_LABEL_QQ                1050
#define IDC_LABEL_QUERY                 1051
#define IDC_ACL_RADIO_DENYIN            1054
#define IDC_ACL_RADIO_DENYALL           1055
#define IDC_LIST_NET                    1056
#define IDC_NET_IP_ARIA_LABLE_END_IP    1056
#define IDC_LABEL_DENYIN                1057
#define IDC_LABEL_TIME                  1057
#define IDC_SYSTEM_SET_SET_LABLE        1058
#define IDC_LABEL_DENYOUT               1058
#define IDC_SYSTEM_SET_UNIT_LABLE       1059
#define IDC_BUTTON_CLS                  1059
#define IDC_BUTTON_BACK                 1060
#define IDC_ABOUT_LABLE_TITLE           1061
#define IDC_BUTTON_NEXT                 1061
#define IDC_LIST1                       1062
#define IDC_LABEL_FROM                  1063
#define IDC_LIST_DIR                    1063
#define IDC_LIST2                       1063
#define IDC_LABEL_TO                    1064
#define IDC_LIST_TIME                   1064
#define IDC_LIST3                       1064
#define IDC_LIST_ACTION                 1065
#define IDC_LIST4                       1065
#define IDC_LIST5                       1066
#define IDC_BUTTON_TORJAN               1067
#define IDC_NET_IP_ARIA_IP_START        1067
#define IDC_SET_TIME_TIME_START         1068
#define IDC_TORJAN_STATUS               1068
#define IDC_NET_IP_ARIA_IP_END          1068
#define IDC_SET_TIME_TIME_END           1069
#define IDC_BUTTON_FILE                 1070
#define IDC_LABEL_0                     1070
#define IDC_LABEL_TIME_START            1071
#define IDC_FILE_STATUS                 1071
#define IDC_LABEL_TIME_END              1072
#define IDC_LABEL_1                     1073
#define IDC_LABEL_2                     1074
#define IDC_NET_IP_ARIA_LABLE_START_IP  1074
#define IDC_LABEL_3                     1075
#define IDC_LABEL_4                     1076
#define IDC_LABEL_5                     1077
#define IDC_LABEL_6                     1078
#define IDC_REG_COMBO_GENDER            1080
#define IDC_PAYFOR_FIREWALL             1081
#define IDC_PAYFOR_WAY                  1082
#define IDC_LABEL_TORJAN_FRAME          1083
#define IDC_REG_TIME_BIRTHDAY           1083
#define IDC_LABEL_FILE_FRAME            1084
#define IDC_REG_COMBO_METIER            1084
#define IDC_PAYFOR_SORUCECODE           1085
#define IDC_LABEL_TORJAN                1086
#define IDC_REG_COMBO_DEGREE            1086
#define IDC_LABEL_FILE                  1087
#define IDC_REG_COMBO_SALARY            1087
#define IDC_LABEL_TORJAN_STATUS         1088
#define IDC_REG_LABEL_NAME              1088
#define IDC_LABEL_FILE_STATUS           1089
#define IDC_REG_LABEL_EMAIL             1089
#define IDC_REG_EDIT_NAME               1090
#define IDC_PAYFOR_ANTIVIRUS            1091
#define IDC_SOFTWARE_REQUEST            1092
#define IDC_LABEL_ADVANCE               1093
#define IDC_REG_EDIT_ZIP                1093
#define IDC_LABEL_ACL_APP_ADD           1094
#define IDC_REG_EDIT_DUTY               1094
#define IDC_LABEL_BASE                  1095
#define IDC_REG_EDIT_INC                1095
#define IDC_LABEL_EXPLAIN               1096
#define IDC_REG_EDIT_QQ                 1096
#define IDC_LABEL_INFO                  1097
#define IDC_PAYFOR_DOCUMENTS            1097
#define IDC_BITMAP_INFO                 1098
#define IDC_GET_WAY                     1098
#define IDC_LABEL_INFO2                 1099
#define IDC_REG_EDIT_CITY               1099
#define IDC_EDIT_WEB                    1100
#define IDC_EDIT_OFFEN_TO_WEB           1100
#define IDC_REG_LABEL_EMAIL2            1101
#define IDC_USED_SOURCE_LABEL           1102
#define IDC_OS                          1103
#define IDC_PAYFOR_FIREWALL3            1104
#define IDC_USED_SOURCE                 1104
#define IDC_EDIT_COSTOM                 1105
#define IDC_USED_SOURCE_LABEL2          1105
#define IDC_LABEL_COSTOM                1106
#define IDC_RADIO_DENY                  1110
#define IDC_RADIO_DENY_AND_ADD_ACL      1111
#define IDC_LIST_INFO                   1112
#define IDC_RADIO_PASS                  1113
#define IDC_FRAME_ACTION                1118
#define IDC_CHECK_QUERY                 1119
#define IDC_APP_ICON                    1120
#define IDC_BUTTON1                     1122
#define IDC_LIST_APP                    1123
#define IDC_LIST_NNB                    1124
#define IDAPPLY                         1124
#define IDC_LIST_ICMP                   1125
#define IDC_BUTTON_REGISTER             1125
#define IDC_STATUS                      1126
#define IDC_REMAIN_TIME                 1127
#define IDC_IN_DATA                     1128
#define IDC_OUT_DATA                    1129
#define IDC_DENY_PACKETS                1130
#define IDC_PASS_PACKETS                1131
#define IDC_SECURITY_LABEL              1132
#define IDC_CURRENT_SECURITY            1133
#define IDC_CURRENT_SECURITY2           1134
#define IDC_LABEL_STATUS                1134
#define IDC_CURRENT_SECURITY3           1135
#define IDC_ABOUT_LABLE                 1135
#define IDC_LABEL_RULE                  1136
#define IDC_ABOUT_LABLE2                1136
#define IDC_WORK_MODE_APP               1137
#define IDC_ABOUT_LABLE3                1137
#define IDC_WORK_MODE_WEB               1138
#define IDC_CHECK_NET_COMMAND           1138
#define IDC_WORK_MODE_NNB               1139
#define IDC_EDIT_UPDATE_INTERAL         1139
#define IDC_WORK_MODE_ICMP              1140
#define IDC_BUTTON_CHECK_NET_COMMAND    1140
#define IDC_CURRENT_SECURITY4           1141
#define IDC_USE_FIREWALL                1141
#define IDC_USE_ANTIVIRUS               1142
#define IDC_BUTTON2                     1142
#define IDC_HACK                        1143
#define IDC_VIRUS                       1144
#define IDC_CHECK_PAYFOR_FIREWALL       1145
#define IDC_CHECK_PAYFOR_ANTIVIRUS      1146
#define IDC_LIKE_NET_TEC                1147
#define IDC_CHECK_PAYFOR_SORUCECODE     1148
#define IDC_CHECK_PAYFOR_DOCUMENTS      1149
#define IDC_CAN_PAYFOR_BOOK             1150
#define IDC_CHECK_OFFEN_TO_WEB          1151
#define IDC_AD                          1152
#define IDC_WEB                         1153
#define IDC_CHECK_GET_WAY               1154
#define IDC_CHECK_SOFTWARE_REQUEST      1155
#define IDC_CHECK_PAYFOR_WAY            1156
#define ID_CONTROL_FRAME                32779
#define ID_FILTER                       32780
#define ID_DENY_ALL                     32781
#define ID_PASS_ALL                     32782

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32783
#define _APS_NEXT_CONTROL_VALUE         1154
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
