//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by HookCom.rc
//
#define IDI_ICON_SHOW_METHODS_ADDRESS   101
#define IDD_DIALOG_SHOW_METHODS_ADDRESS 102
#define IDD_DIALOG_COM_INTERACTION      103
#define IDI_ICON_REMOTE_CALL            104
#define IDD_DIALOG_REMOTE_CALL_RESULT   105
#define IDD_DIALOG_IDISPATCH_SELECTION  106
#define IDI_ICON_EDIT                   176
#define IDC_TREE_METHODS_ADDRESS        1001
#define IDC_EDIT_CLSID                  1002
#define IDC_EDIT_IID                    1003
#define IDC_BUTTON_EDIT_ASSOCIATED_IID_FILE 1004
#define IDC_CHECK_TRY_IDISPATCH_PARSING 1005
#define IDC_CHECK_DONT_ADD_OBJECT_POINTER 1006
#define IDC_BUTTON_SAVE                 1007
#define IDC_BUTTON_QUERY_NEW_INTERFACE  1008
#define IDC_TREE_COM_INTERACTION        1009
#define IDC_COMBO_INTERFACES            1010
#define IDC_EDIT_OBJECT_ADDRESS         1011
#define IDC_RADIO_USE_FUNCTION_NAME     1012
#define IDC_COMBO_METHODS               1013
#define IDC_RADIO_USE_VTBL_INDEX        1014
#define IDC_EDIT_VTBL_INDEX             1015
#define IDC_BUTTON_PROPERTY_PAGE        1016
#define IDC_EDIT_QUERY_NEW_INTERFACE    1017
#define IDC_BUTTON_REFRESH              1018
#define IDC_EDIT_CALL                   1019
#define IDC_EDIT_REMOTE_CALL_RESULT     1020
#define IDC_EDIT_REMOTE_CALL_EAX        1021
#define IDC_EDIT_REMOTE_CALL_EBX        1022
#define IDC_EDIT_REMOTE_CALL_ECX        1023
#define IDC_EDIT_REMOTE_CALL_EDX        1024
#define IDC_EDIT_REMOTE_CALL_ESI        1025
#define IDC_EDIT_REMOTE_CALL_EDI        1026
#define IDC_EDIT_REMOTE_CALL_EFL        1027
#define IDC_CHECK_REMOTE_CALL_SHOW_OUTPUT_REGISTERS 1028
#define IDC_CHECK_DO_CALL_IN_THREAD_OWNER 1029
#define IDC_EDIT_IDISPATCH_MODIFY       1031
#define IDC_BUTTON_IDISPATCH_MODIFY     1032
#define IDC_EDIT_FILE_NAME              1033
#define IDC_STATIC_INTERFACE_NAME       1034
#define IDC_BUTTON_CHECK_ALL            1035
#define IDC_BUTTON_UNCHECK_ALL          1036
#define IDC_LIST_IDISPATCH              1037
#define IDC_LIST_IDISPATCH_MODIFY       1038
#define IDC_CHECK_SAVE_SETTINGS_UNDER_FILE 1039
#define IDC_EDIT_REMOTE_CALL_TIMEOUT    1040

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1041
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
