//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by c:\sudhir\netdefender\code\netdefender 1.5\Res\Fire.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_FIRE_FORM                   101
#define CG_IDS_SOCKETS_INIT_FAILED      102
#define IDR_MAINFRAME                   128
#define IDI_MAINFRAME                   128
#define IDR_FIRETYPE                    129
#define IDD_ADDRULE                     130
#define IDR_MENU1                       131
#define IDD_PORTSCAN_FORM               134
#define IDI_LED_GREEN                   140
#define IDI_LED_RED                     141
#define IDI_LED_OFF                     142
#define IDD_PROCESS_VIEW                144
#define IDI_ICON_UNK_PROCESS            145
#define IDI_ICON2                       146
#define IDI_ICON_PROTO                  146
#define IDB_COLORTOOLBAR                148
#define IDB_TOOLBARDISABLE              149
#define IDB_BITMAP2                     151
#define IDB_CLIENTICONS_EX              151
#define IDR_BMP2                        159
#define IDB_CANCEL                      163
#define IDB_BITMAP1                     164
#define IDB_OK                          164
#define IDR_MENU_SRCIP                  166
#define IDR_MENU_DESTIP                 167
#define IDR_MENU_SRC_PORT               168
#define IDR_MENU_DESTPORT               170
#define IDB_BITMAP3                     170
#define IDB_BMP_BK                      170
#define IDC_BLOCKALL                    1000
#define IDC_BLOCKPING                   1001
#define IDC_ADDRULE                     1002
#define IDC_START                       1003
#define IDC_ALLOWALL                    1004
#define IDC_SADD                        1005
#define IDC_DADD                        1006
#define IDC_SPORT                       1007
#define IDC_DPORT                       1008
#define IDC_COMBO1                      1009
#define IDC_COMBO2                      1010
#define IDC_ADD                         1011
#define IDC_ADDSAVE                     1012
#define IDC_STARWARS                    1014
#define IDC_IP_ADDRESS                  1015
#define IDC_STATIC_IP                   1016
#define IDC_BUTTON_SCAN                 1017
#define IDC_BUTTON_STOP                 1018
#define IDC_LIST_RESULT                 1020
#define IDC_PROGRESS                    1021
#define IDC_RADIO_SINGLE                1022
#define IDC_RADIO_RANGE                 1023
#define IDC_EDIT_SINGLE_PORT            1024
#define IDC_EDIT_SINGLE_PORT_FROM       1025
#define IDC_EDIT_ATTEMPTS               1026
#define IDC_EDIT_SINGLE_PORT_TO         1027
#define IDC_STATUS_BAR                  1028
#define IDC_MSFLEXGRID1                 1029
#define IDC_VIEWRULES                   1030
#define IDC_LIST_PROCESS_VIEW           1032
#define IDC_STATIC_SCAN_RESULT          1033
#define IDC_STATIC_RUN_APP              1034
#define IDC_STATIC_RULE                 1035
#define IDC_STATIC_ADD_NEW_RULE         1036
#define IDC_STATIC_SRC_ADD              1037
#define IDC_STATIC_DEST_ADD             1038
#define IDC_STATIC_SRC_PORT             1039
#define IDC_STATIC_DEST_PORT            1040
#define IDC_STATIC_ACTION               1041
#define IDC_STATIC_PROTOCOL             1042
#define IDC_BUT_EDIT_RULE               1043
#define IDC_BUT_REMOVE_RULE             1044
#define IDC_BUT_ADDRULE                 1045
#define IDC_BUTTON1                     1047
#define IDC_REREGISTER_RULE             1047
#define IDC_BUT_SRCIP_PICKER            1047
#define IDC_BUT_DEST_IP_PICKER          1048
#define IDC_BUT_DEST_PORTPICKER         1049
#define IDC_BUT_SRC_PORT_PICKER         1050
#define ID_POPUP_MINIMIZE               32772
#define ID_POPUP_MAXIMIZE               32773
#define ID_EXIT                         32779
#define ID_HELP_CONTENTS                32780
#define ID_POPUP_EXIT                   32786
#define ID_ICON                         32788
#define ID_TOOLS_PORTSCANNER            32789
#define ID_Start                        32791
#define ID_STOP                         32792
#define ID_BLOCKALL                     32793
#define ID_ALLOWALL                     32794
#define ID_BLOCKPING                    32795
#define ID_TOOLS_BLOCKAPPLICATION       32796
#define ID_BUTTON32797                  32797
#define ID_BUTTON32798                  32798
#define ID_BUTTON32799                  32799
#define ID_BUTTON32800                  32800
#define ID_APP_APPLBLOCK                32801
#define ID_HELP_VISITNETDEFENDERHOMEPAGE 32803
#define ID__SRCIPMYMACHINE              32810
#define ID__SRCIPANYMACHINE             32811
#define ID__DESTANYMACHINE              32812
#define ID__DESTMYMACHINE               32814
#define ID__ANYPORT                     32815
#define ID__ANYPORT32816                32816
#define ID__FTPCOMMAND                  32817
#define ID__SSH                         32818
#define ID__TELNET                      32819
#define ID__SMTP                        32820
#define ID__TELNET32821                 32821
#define ID__FTP                         32822
#define ID__DNS                         32823
#define ID__BOOTP                       32824
#define ID__HTTP                        32825
#define ID__POP3                        32826
#define ID__NNTP                        32827
#define ID__NETBIOSNAMESERVICENBTSTAT   32828
#define ID__SOCKS                       32829
#define ID__ANYPORT1                    32830
#define ID__FTP1                        32831
#define ID__SSH1                        32832
#define ID__TELNET328211                32833
#define ID__SMTP1                       32834
#define ID__DNS1                        32835
#define ID__BOOTP1                      32836
#define ID__HTTP1                       32837
#define ID__POP31                       32838
#define ID__NNTP1                       32839
#define ID__NETBIOSNAMESERVICENBTSTAT1  32840
#define ID__SOCKS1                      32841
#define ID_INDICATOR_ONLINELED          59142
#define ID_INDICATOR_OFFLINELED         59143

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        171
#define _APS_NEXT_COMMAND_VALUE         32842
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
