//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MonitoringFileBuilder.rc
//
#define IDD_DIALOG_MAIN                 101
#define IDI_ICON_MONITORINGFILEBUILDER  102
#define IDD_DIALOG_FUNCTIONS_SELECTION  103
#define IDI_ICON_CANCEL                 104
#define IDI_ICON_WARNINGS_AND_ERRORS    105
#define IDD_DIALOG_WARNING_AND_ERRORS   106
#define IDR_EXE_FIND_STACK_BY_CALL      107
#define IDC_EDIT_INPUT_FILE             1001
#define IDC_BUTTON_BROWSE_INPUT         1002
#define IDC_EDIT_OUTPUT_FILE            1003
#define IDC_BUTTON_BROWSE_OUTPUT        1004
#define IDC_RADIO_IMPORT_TABLE          1005
#define IDC_RADIO_EXPORT_TABLE          1006
#define IDC_EDIT_LOGS                   1007
#define IDC_BUTTON_CHECK_ERROR          1008
#define IDC_CHECK_CALL_TO_GUESS_NB_PARAM 1009
#define IDC_EDIT_OLD_MONITORING_FILE    1010
#define IDC_BUTTON_BROWSE_OLD_MONITORING_FILE 1011
#define IDC_LIST_IMPORTED_LIBRARIES     1012
#define IDC_LIST_IMPORTED_EXPORTED_FUNCTIONS 1013
#define IDC_BUTTON_CHECK_ALL            1014
#define IDC_BUTTON_UNCHECK_ALL          1015
#define IDC_STATIC_IMPORTED_EXPORTED_FUNCTIONS 1016
#define IDC_STATIC_IMPORTED_LIBRARIES   1017
#define IDC_CHECK_ONLINE_MSDN           1018
#define IDC_BUTTON_CHECK_SELECTED       1019
#define IDC_BUTTON_UNCHECK_SELECTED     1020
#define IDC_CHECK_CHECK_TROUBLES        1021
#define IDC_PROGRESS                    1022
#define IDC_BUTTON_UPDATE               1023
#define IDC_CHECK_USEPROXY              1024
#define IDC_CHECK_FIRST_BYTES_ANALYSIS  1025
#define IDC_BUTTON_GENERATE             1026
#define IDC_RADIO_FULL_GENERATION       1027
#define IDC_RADIO_PARTIAL_GENERATION    1028
#define IDC_RADIO_FULL_UPDATE           1029
#define IDC_RADIO_UPDATE_BYTES_ANALYSIS 1030
#define IDC_RADIO_UPDATE_REMOVE_BYTES_ANALYSIS 1031
#define IDC_BUTTON_WARNING_ERROR_MSG    1032
#define IDC_EDIT_WARNINGS_AND_ERRORS    1033
#define IDC_COMBO_WIZARD_FUNC_SEARCH    1034
#define IDC_RADIO_PARSE_NET             1035
#define IDC_RADIO_PARSE_DEBUG_FILE      1036
#define IDC_GROUP_UPDATE                1037
#define IDC_GROUP_DETECT                1038
#define IDC_GROUP_OPTION                1039
#define IDC_RADIO_PARSE_COM_TYPE_LIBRARY 1040
#define IDC_RADIO_PARSE_COM_ALL_REGISTERED_TYPE_LIBRARY 1041
#define IDC_BUTTON_CHECK_ALL_IMPORTED_LIBS 1042
#define IDC_BUTTON_UNCHECK_ALL_IMPORTED_LIBS 1043

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        112
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
