//
// win32k.sys stub for exports
//
extern "C"
{

	 void BRUSHOBJ_hGetColorTransform
(){} void BRUSHOBJ_pvAllocRbrush
(){} void BRUSHOBJ_pvGetRbrush
(){} void BRUSHOBJ_ulGetBrushColor
(){} void CLIPOBJ_bEnum
(){} void CLIPOBJ_cEnumStart
(){} void CLIPOBJ_ppoGetPath
(){} void EngAcquireSemaphore
(){} void EngAllocMem
(){} void EngAllocPrivateUserMem
(){} void EngAllocSectionMem
(){} void EngAllocUserMem
(){} void EngAlphaBlend
(){} void EngAssociateSurface
(){} void EngBitBlt
(){} void EngBugCheckEx
(){} void EngCheckAbort
(){} void EngClearEvent
(){} void EngComputeGlyphSet
(){} void EngControlSprites
(){} void EngCopyBits
(int,int,int,int,int,int){} void EngCreateBitmap
(int,int,int,int,int,int){} void EngCreateClip
(){} void EngCreateDeviceBitmap
(){} void EngCreateDeviceSurface
(){} void EngCreateDriverObj
(){} void EngCreateEvent
(){} void EngCreatePalette
(){} void EngCreatePath
(){} void EngCreateSemaphore
(){} void EngCreateWnd
(){} void EngDebugBreak
(){} void EngDebugPrint
(int,int,int){} void EngDeleteClip
(){} void EngDeleteDriverObj
(){} void EngDeleteEvent
(){} void EngDeleteFile
(){} void EngDeletePalette
(){} void EngDeletePath
(){} void EngDeleteSafeSemaphore
(){} void EngDeleteSemaphore
(){} void EngDeleteSurface
(int){} void EngDeleteWnd
(){} void EngDeviceIoControl
(){} void EngDitherColor
(){} void EngDxIoctl
(){} void EngEnumForms
(){} void EngEraseSurface
(int,int,int){} void EngFileIoControl
(){} void EngFileWrite
(){} void EngFillPath
(int,int,int,int,int,int,int){} void EngFindImageProcAddress
(int,int){} void EngFindResource
(){} void EngFntCacheAlloc
(){} void EngFntCacheFault
(){} void EngFntCacheLookUp
(){} void EngFreeMem
(){} void EngFreeModule
(){} void EngFreePrivateUserMem
(){} void EngFreeSectionMem
(){} void EngFreeUserMem
(){} void EngGetCurrentCodePage
(){} void EngGetCurrentProcessId
(){} void EngGetCurrentThreadId
(){} void EngGetDriverName
(){} void EngGetFileChangeTime
(){} void EngGetFilePath
(){} void EngGetForm
(){} void EngGetLastError
(){} void EngGetPrinter
(){} void EngGetPrinterData
(){} void EngGetPrinterDataFileName
(){} void EngGetPrinterDriver
(){} void EngGetProcessHandle
(){} void EngGetTickCount
(){} void EngGetType1FontList
(){} void EngGradientFill
(){} void EngHangNotification
(){} void EngInitializeSafeSemaphore
(){} void EngIsSemaphoreOwned
(){} void EngIsSemaphoreOwnedByCurrentThread
(){} void EngLineTo
(int,int,int,int,int,int,int,int,int){} void EngLoadImage
(int){} void EngLoadModule
(){} void EngLoadModuleForWrite
(){} void EngLockDirectDrawSurface
(){} void EngLockDriverObj
(){} void EngLockSurface
(int){} void EngLpkInstalled
(){} void EngMapEvent
(){} void EngMapFile
(int,int,int){} void EngMapFontFile
(){} void EngMapFontFileFD
(){} void EngMapModule
(){} void EngMapSection
(){} void EngMarkBandingSurface
(){} void EngModifySurface
(){} void EngMovePointer
(){} void EngMulDiv
(){} void EngMultiByteToUnicodeN
(){} void EngMultiByteToWideChar
(){} void EngNineGrid
(){} void EngPaint
(){} void EngPlgBlt
(){} void EngProbeForRead
(){} void EngProbeForReadAndWrite
(){} void EngQueryDeviceAttribute
(){} void EngQueryLocalTime
(){} void EngQueryPalette
(){} void EngQueryPerformanceCounter
(){} void EngQueryPerformanceFrequency
(){} void EngQuerySystemAttribute
(){} void EngReadStateEvent
(){} void EngReleaseSemaphore
(){} void EngRestoreFloatingPointState
(){} void EngSaveFloatingPointState
(){} void EngSecureMem
(){} void EngSetEvent
(){} void EngSetLastError
(){} void EngSetPointerShape
(){} void EngSetPointerTag
(){} void EngSetPrinterData
(){} void EngSort
(){} void EngStretchBlt
(){} void EngStretchBltROP
(){} void EngStrokeAndFillPath
(){} void EngStrokePath
(){} void EngTextOut
(){} void EngTransparentBlt
(){} void EngUnicodeToMultiByteN
(){} void EngUnloadImage
(int){} void EngUnlockDirectDrawSurface
(){} void EngUnlockDriverObj
(){} void EngUnlockSurface
(int){} void EngUnmapEvent
(){} void EngUnmapFile
(int){} void EngUnmapFontFile
(){} void EngUnmapFontFileFD
(){} void EngUnsecureMem
(){} void EngWaitForSingleObject
(){} void EngWideCharToMultiByte
(){} void EngWritePrinter
(){} void _except_handler2
(){} void FLOATOBJ_Add
(){} void FLOATOBJ_AddFloat
(){} void FLOATOBJ_AddFloatObj
(){} void FLOATOBJ_AddLong
(){} void FLOATOBJ_Div
(){} void FLOATOBJ_DivFloat
(){} void FLOATOBJ_DivFloatObj
(){} void FLOATOBJ_DivLong
(){} void FLOATOBJ_Equal
(){} void FLOATOBJ_EqualLong
(){} void FLOATOBJ_GetFloat
(){} void FLOATOBJ_GetLong
(){} void FLOATOBJ_GreaterThan
(){} void FLOATOBJ_GreaterThanLong
(){} void FLOATOBJ_LessThan
(){} void FLOATOBJ_LessThanLong
(){} void FLOATOBJ_Mul
(){} void FLOATOBJ_MulFloat
(){} void FLOATOBJ_MulFloatObj
(){} void FLOATOBJ_MulLong
(){} void FLOATOBJ_Neg
(){} void FLOATOBJ_SetFloat
(){} void FLOATOBJ_SetLong
(){} void FLOATOBJ_Sub
(){} void FLOATOBJ_SubFloat
(){} void FLOATOBJ_SubFloatObj
(){} void FLOATOBJ_SubLong
(){} void FONTOBJ_cGetAllGlyphHandles
(){} void FONTOBJ_cGetGlyphs
(){} void FONTOBJ_pfdg
(){} void FONTOBJ_pifi
(){} void FONTOBJ_pjOpenTypeTablePointer
(){} void FONTOBJ_pQueryGlyphAttrs
(){} void FONTOBJ_pvTrueTypeFontFile
(){} void FONTOBJ_pwszFontFilePaths
(){} void FONTOBJ_pxoGetXform
(){} void FONTOBJ_vGetInfo
(){} void _global_unwind2
(){} void HeapVidMemAllocAligned
(){} void HT_ComputeRGBGammaTable
(){} void HT_Get8BPPFormatPalette
(){} void HT_Get8BPPMaskPalette
(){} void _itoa
(){} void _itow
(){} void _local_unwind2
(){} void PALOBJ_cGetColors
(){} void PATHOBJ_bCloseFigure
(int){} void PATHOBJ_bEnum
(){} void PATHOBJ_bEnumClipLines
(){} void PATHOBJ_bMoveTo
(int,int,int){} void PATHOBJ_bPolyBezierTo
(){} void PATHOBJ_bPolyLineTo
(int,int,int){} void PATHOBJ_vEnumStart
(){} void PATHOBJ_vEnumStartClipLines
(){} void PATHOBJ_vGetBounds
(){} void RtlAnsiCharToUnicodeChar
(){} void RtlMultiByteToUnicodeN
(){} void RtlRaiseException
(){} void RtlUnicodeToMultiByteN
(){} void RtlUnicodeToMultiByteSize
(){} void RtlUnwind
(){} void RtlUpcaseUnicodeChar
(){} void RtlUpcaseUnicodeToMultiByteN
(){} void STROBJ_bEnum
(){} void STROBJ_bEnumPositionsOnly
(){} void STROBJ_bGetAdvanceWidths
(){} void STROBJ_dwGetCodePage
(){} void STROBJ_fxBreakExtra
(){} void STROBJ_fxCharacterExtra
(){} void STROBJ_vEnumStart
(){} void VidMemFree
(){} void WNDOBJ_bEnum
(){} void WNDOBJ_cEnumStart
(){} void WNDOBJ_vSetConsumer
(){} void XFORMOBJ_bApplyXform
(){} void XFORMOBJ_iGetFloatObjXform
(){} void XFORMOBJ_iGetXform
(){} void XLATEOBJ_cGetPalette
(){} void XLATEOBJ_hGetColorTransform
(){} void XLATEOBJ_iXlate
(int,int){} void XLATEOBJ_piVector
(){}

void* FindSelfBase();
void* __base()
{
	return FindSelfBase();
}

}

// Entry stub
int DriverEntry(int,int)
{
	return (int)0xc0000001;
}
