#ifndef __FILEFLT_CONTROL_H__
#define __FILEFLT_CONTROL_H__

#define FILEFLT_CONTROL_NO     0x00
#define FILEFLT_CONTROL_YES    0x01


#define FILEFLT_VIRTUALPC_VIRTUALBOX_USED	FILEFLT_CONTROL_NO
#define FILEFLT_VIRTUALPC_VMWARE_NAT_USED	FILEFLT_CONTROL_NO

#endif /* __FILEFLT_CONTROL_H__ */